### ISSUE TITLE
Support for more than 256 lights

### ISSUE THREAD

**Issue by vdrumsta** [Lord-FEAR/Prismatik-WLED-WiFi#1]
Hi there!

This works great if you set light to 256 or less, but is it possible to modify this for support higher than 256 lights?

Could this be a limitation of this method:
d = self.lp.getColoursFromAll()

Any help is appreciated!
Many thanks

**Comment by Lord-FEAR** [comment]
Hello!
Now the program uses the WARLS protocol which is limited to 255 LEDs.
https://github.com/Aircoookie/WLED/wiki/E1.31-&-UDP-Realtime-Control#udp-realtime

Perhaps you can rewrite the program to the DNRGB protocol.
I haven’t figured it out yet and I don’t have time for this yet.

**Comment by Lord-FEAR** [comment]
> Hi there!
> 
> This works great if you set light to 256 or less, but is it possible to modify this for support higher than 256 lights?
> 
> Could this be a limitation of this method:
> d = self.lp.getColoursFromAll()
> 
> Any help is appreciated!
> Many thanks

Added support for 490 LEDs https://github.com/Lord-FEAR/Prismatik-WLED-WiFi/commit/b206c3c00ebfb743489e14300465f182f0c936d9
