### ISSUE TITLE
How can i run configuration wizard? there is no port to config

### ISSUE THREAD

**Issue by tihoangyeudau** [Lord-FEAR/Prismatik-WLED-WiFi#2]
How can i run configuration wizard? there is no port to config. im stuck in this after all you guide

**Comment by Lord-FEAR** [comment]
Standard port 21324 If you did not change it in the **Sync Interface** then everything should work immediately without additional settings and changing the address 192.168.1.255 unless of course you have a 192.168.X.255 subnet or another.
![7](https://user-images.githubusercontent.com/5351661/70806600-86840b80-1ddd-11ea-8682-126d20ff63df.png)

**Comment by tihoangyeudau** [comment]
thank you i can do it!
