### ISSUE TITLE
This Plugin does not run on MAC

### ISSUE THREAD

**Issue by tihoangyeudau** [Lord-FEAR/Prismatik-WLED-WiFi#3]
This plugin works well on Win, but on Mac, after i install python 3.7.5, future, boltons, and py-lightpark, and copy it into the Prismatik, it already shows not running. did you test it on MAC?
https://ibb.co/Nxhk3yR

**Comment by Lord-FEAR** [comment]
No, I did not check it on the MAC.
Try to launch the console in the directory with the file WLED_WiFi.py and run it through python. It will give an error to the console because of which the plugin does not work

**Comment by tihoangyeudau** [comment]
> No, I did not check it on the MAC.
> Try to launch the console in the directory with the file WLED_WiFi.py and run it through python. It will give an error to the console because of which the plugin does not work

here it is:
https://ibb.co/hYwgMwM

**Comment by Lord-FEAR** [comment]
It's simple, lightpack is not installed.
`pip install future boltons py-lightpack`
this should solve possible problems

_My antivirus swears heavily on your image links_

**Comment by tihoangyeudau** [comment]
The problem is that I have already installed `pip install future boltons py-lightpackit` and the error still appears

**Comment by tihoangyeudau** [comment]
> _My antivirus swears heavily on your image links_

im sorry about this. i will use something else

**Comment by Lord-FEAR** [comment]
I do not know the solution to this problem, perhaps it is better to ask in the py-lightpackit repository.

**Comment by tihoangyeudau** [comment]
> I do not know the solution to this problem, perhaps it is better to ask in the py-lightpackit repository.

okay thank you

**Comment by tihoangyeudau** [comment]
> I do not know the solution to this problem, perhaps it is better to ask in the py-lightpackit repository.

I reinstalled mac os, and tried to setup python 3.7.5 as defaut , then used python launcher to open WLED_WiFi.py and it worked. but in prismatik, wled plugin still was not running.

**Comment by joselito11** [comment]
I get this error, but I have changed IP and port in .ini file to 21324, why get error with port 3636:
```
python3 WLED_WiFi.py
CannotConnectError("Could not connect to localhost:3636 (without an API key), caused by ConnectionRefusedError(111, 'Connection refused')")
```

**Comment by Aputze** [comment]
Stuck with weird error
can any1 help 
![image](https://user-images.githubusercontent.com/56610049/103592781-a1e81a00-4efc-11eb-8084-6eea7ce0a92b.png)

**Comment by Lord-FEAR** [comment]
> Застрял со странной ошибкой,
> может помочь any1
> ![образ](https://user-images.githubusercontent.com/56610049/103592781-a1e81a00-4efc-11eb-8084-6eea7ce0a92b.png)

I can't say for sure and there is no way to check for MAC. Possibly a bug in the new version of python 3.9. Now I tested it for python 3.8 and [Lightpack 5.11.2.27](https://github.com/psieg/Lightpack/releases) and py-lightpack v2.2.0 for Windows, everything works without errors.

**Comment by Aputze** [comment]
Благодарю за ответ￼

**Comment by Aputze** [comment]
Я вообщето работаю под системой Windows 😅

**Comment by Aputze** [comment]
Наверное не установил добавку как надо￼
