### ISSUE TITLE
Issue with many led pixels

### ISSUE THREAD

**Issue by tihoangyeudau** [Lord-FEAR/Prismatik-WLED-WiFi#4]
When i set 300 led pixels on wled and prismatik. a lot of led pixels are light and not light discretely at the end of the led strip.

**Comment by Lord-FEAR** [comment]
The program supports a maximum of 256 LEDs. The number of LEDs is limited by the WARLS protocol in the WLED firmware and the py-lightpack module.
There may be ways to increase the number of LEDs, but I don’t have time for this project.
To simplify communication, you can communicate in a discord - https://discord.gg/2F2X9VA

**Comment by tihoangyeudau** [comment]
thank you so much!

**Comment by Lord-FEAR** [comment]
> When i set 300 led pixels on wled and prismatik. a lot of led pixels are light and not light discretely at the end of the led strip.

Added support for 490 LEDs https://github.com/Lord-FEAR/Prismatik-WLED-WiFi/commit/b206c3c00ebfb743489e14300465f182f0c936d9

**Comment by tihoangyeudau** [comment]
> > When i set 300 led pixels on wled and prismatik. a lot of led pixels are light and not light discretely at the end of the led strip.
> 
> Added support for 490 LEDs [b206c3c](https://github.com/Lord-FEAR/Prismatik-WLED-WiFi/commit/b206c3c00ebfb743489e14300465f182f0c936d9)

You are my hero! Love u
