### ISSUE TITLE
Plugin failure

### ISSUE THREAD

**Issue by kirkyb** [Lord-FEAR/Prismatik-WLED-WiFi#5]
Hi. I've installed all the pre-requisites as per your tutorial but I can't seem  to get your plug in to work "Error (not running)"

Please advise on the settings I should use in the .ini file?
This is what I've got....

[Main]
Name=WLED_WiFi
Execute=C:\Users\kirky\AppData\Local\Programs\Python\Python37\python.exe WLED_WiFi.py
Icon=icon.png
Author=Lord FEAR
Version=0.2
Description=Adds DRGB protocol for WLED

[WLED]
UDP_IP_ADDRESS=192.168.0.57
UDP_PORT_NO=21324
FPS=66

**Comment by Lord-FEAR** [comment]
Open the plugin folder
`C:\Users\kirky\Prismatik\Plugins\WLED_WiFi`
And run Windows PowerShell or CMD
using your own startup path (usually it’s not necessary to use the full path and just `python.exe WLED_WiFi.py` is enough)
`C:\Users\kirky\AppData\Local\Programs\Python\Python37\python.exe WLED_WiFi.py`
https://cdn.discordapp.com/attachments/665076848480485417/665081126695731210/unknown.png

**Comment by kirkyb** [comment]
Hi thanks for getting back to me. I've done as you have suggested and I am still seeing the same error message. FYI I have full admin rights and have installed Prismatic with admin privileges. Resinstalling Python 3.7 hasn't helped.

**Comment by Lord-FEAR** [comment]
You never said that you issued code execution in PowerShell

**Comment by kirkyb** [comment]
Hi yes, I did as you advised using admin command prompt. The command appeared to progress but did not display any confirmation that anything had worked. The plug in still showed error

**Comment by Lord-FEAR** [comment]
Have you tried running PowerShell when a WLED LED strip device is turned on? If there are no errors in PowerShell then everything should work. If everything works, then the settings most likely do not correctly indicate `Execute=C:\Users\kirky\AppData\Local\Programs\Python\Python37\python.exe WLED_WiFi.py` Попробуйте заменить на `Execute=python.exe WLED_WiFi.py`

**Comment by kirkyb** [comment]
Silly mistake, I had been using - instead of _

Seperate issue now though is that the plugin appears but I can't get it to run. The IP address of my esp8266 is correctly in the WLED_Wifi.ini file and the port is correct too

**Comment by kirkyb** [comment]
I've figured out that I needed to use the full paths to both python.exe and WLED_Wifi.py for them to work in powershell. After creating a fake Adalight profile based on my setup, I was able to successfully use Prismatik, very impressive.
All I need to do now is figure out why the plugin isn't working and also reduce the small amount of lag between image and LED output

**Comment by Aputze** [comment]
Can anyone help..
Cant get the plugin running
![image](https://user-images.githubusercontent.com/56610049/105431152-be56b700-5c5d-11eb-86fa-591c2a21debd.png)

**Comment by Aputze** [comment]
![image](https://user-images.githubusercontent.com/56610049/105431440-46d55780-5c5e-11eb-8df4-4493ead5b0a9.png)

**Comment by Lord-FEAR** [comment]
Probably a bug in lightpack, try installing the "future" library which contains the "past" module
`pip install future`

**Comment by Aputze** [comment]
Done! 
But still plugin NOT RUNNING 
![image](https://user-images.githubusercontent.com/56610049/105483133-0b647880-5cb2-11eb-88e9-59f80917db30.png)

**Comment by Lord-FEAR** [comment]
What does the console output show?
boltons installed?
`pip install boltons`

**Comment by Aputze** [comment]
Hey sorry for late reply.
I built a new machine but unfortunately same error,
![image](https://user-images.githubusercontent.com/56610049/107161349-df7d0e80-69a4-11eb-95dd-e7b0dcc34266.png)

**Comment by Lord-FEAR** [comment]
> Привет, извините за поздний ответ.
> Я построил новую машину, но, к сожалению, та же ошибка,
> ![образ](https://user-images.githubusercontent.com/56610049/107161349-df7d0e80-69a4-11eb-95dd-e7b0dcc34266.png)

bug in lightpack, try asking here https://github.com/tremby/py-lightpack

**Comment by sanketwayne** [comment]
I did everything, the Plugin is not running, another thing (noob question) should i put my pc IP address in the ini ? because the Nordmcu i am using for ambilight is not showing any Ip address separately.. It would be great if you make a quick video and post the link since you know every nook and cranny of this program ! 

Thanks ^_^
![Screenshot 2024-07-07 121654](https://github.com/Lord-FEAR/Prismatik-WLED-WiFi/assets/105712625/0695142a-6783-4c84-9bcb-bddc81604c4c)

**Comment by Lord-FEAR** [comment]
> I did everything, the Plugin is not running, another thing (noob question) should i put my pc IP address in the ini ? because the Nordmcu i am using for ambilight is not showing any Ip address separately.. It would be great if you make a quick video and post the link since you know every nook and cranny of this program !
> 
> Thanks ^_^ ![Screenshot 2024-07-07 121654](https://private-user-images.githubusercontent.com/105712625/346316333-0695142a-6783-4c84-9bcb-bddc81604c4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDQwNjAsIm5iZiI6MTcyMDQ0Mzc2MCwicGF0aCI6Ii8xMDU3MTI2MjUvMzQ2MzE2MzMzLTA2OTUxNDJhLTY3ODMtNGM4NC05YmNiLWJkZGM4MTYwNGM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMzAyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTY4MDIzZjcyNGY1NTZmMzQ0YTA4MTNhZmUyNDc5ZDk3YzZhNWUwODU3MzhkNjdjNjNiMTBlYmZhNTE3MTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uVAC3YA6wwfm-tuN5_mN2NRds-XabPPpPqQW0WCAbqw)

The plugin is outdated and will not be updated. Use WLED to work with hyperion.
https://github.com/Aircoookie/WLED
